# model
model_config: 'DeepPavlov/rubert-base-cased'
num_classes: 9

# hyperparameters of training
weight_decay: 0.000001
learning_rate: 0.00005
backbone_lr_div: 100
epochs: 10
batch_size: 128
warmup_steps: 5000

# other
max_pad_len: 128

# data ang logging
train_data_path: '../data/goods_classifier/train.csv'
eval_data_path: '../data/goods_classifier/test.csv'
ckpt_url: '/path/to/checkpoint'
logs_dir: 'logs'
exp_name: 'bs_128_wrmp_sch'
num_workers: 16

---
# Config description for each option

